adding docker and cronjob (but hasnt been tested)
AFA-Tooling/GradeSync pull request #13
Opened 2024-10-31 23:25 UTC by jedi-force

### Jira Ticket

GS-22/GS-36
[Jira Ticket]( @https://dashbd.atlassian.net/browse/GS-22/GS-36)

### Description

adding docker and cronjob (but hasnt been tested)

2024-10-31 23:26 UTC, jedi-force commented
merging docker + cronjob (but hasnt been tested)

2024-10-31 23:35 UTC, Mehul-Gandhi requested changes
1. Pull from main. Push the latest changes to this branch.
2. Rename the folder to something like `gradescopeCronJob` instead of `app`
3. Change the requirements.txt
4. Change Dockerfile python version
5. Do testing and ensure this works for Fall 2024. Show the testing output and share redacted info of the spreadsheet.

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/Dockerfile
> +FROM python:3.9-slim
Change this to python 3.11 or 3.12

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/crontab
> +0 * * * * python gradescope_to_spreadsheet.py >> /var/log/cron.log 2>&1
Later, do some tests to see how long the script takes for CS10 Fall 2024, since there are more students in Fall 2024 compared to Summer 2024.

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +SPREADSHEET_ID = "1Ms0PvwUKbph3p29bih-rDBV9EjyI9Ae-T3rGlRDwXqc"
When you get the testing working, provide the spreadsheet with the output with student data and PII hidden.

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +    gradescope_client.prompt_login()
Please pull the latest changes from main. Naveen changed this line of code.

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +    gradescope_client.prompt_login()
And then push to your branch again.

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/requirements.txt
> +httpx==0.27.0
Only include what is actually used for this script. FastAPI, uvicorn, pytest, httpx are not used.

2024-10-31 23:35 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +    gradescope_client.prompt_login()
Make sure you have a `.env` to load the GRADESCOPE_EMAIL and GRADESOPE_PASSWORD.

2024-10-31 23:38 UTC, Mehul-Gandhi commented on app/crontab
> +0 * * * * python gradescope_to_spreadsheet.py >> /var/log/cron.log 2>&1
As in, once an hour might be too frequent and cron job 1 might not be finished when cron job 2 starts. Make sure to have a good number in terms of how often this script reruns.

2024-10-31 23:42 UTC, Mehul-Gandhi commented
Review other comments
https://dancsed.slack.com/archives/C07LCJTJ2BD/p1730147160483339?thread_ts=1730139634.822249&cid=C07LCJTJ2BD
https://dancsed.slack.com/archives/C07LCJTJ2BD/p1730150555800259?thread_ts=1730139634.822249&cid=C07LCJTJ2BD

2024-11-01 04:16 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +def allow_user_to_authenticate_google_account():
This whole function needs to be reworked. This library is depecrated 
https://google-auth.readthedocs.io/en/master/oauth2client-deprecation.html

There is a required manual intervention from a user: If no valid credentials are available and refreshing isn’t possible,
`flow.run_local_server(port=0)` opens a local server on an available port and a browser window, prompting the user to sign in to their Google account and grant the specified permissions.

Please work with Connor on creating a service account for this application. This is critical for deployment and automated cron jobs.
https://developers.google.com/identity/protocols/oauth2/service-account

Our application should not require manual intervention for authentication. GradeView also currently uses a service account and we probably need to make our own service account on GCP.

2024-11-01 04:19 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +def allow_user_to_authenticate_google_account():
See https://github.com/AFA-Tooling/GradeView/blob/main/dbcron/update_bins.py for the service account approach

2024-11-01 04:31 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +def allow_user_to_authenticate_google_account():
In the `.env` file, we should have a variable `SERVICE_ACCOUNT_CREDENTIALS` with the google service account credentials. We will no longer need token.json

2024-11-01 04:38 UTC, Mehul-Gandhi commented on app/gradescope_to_spreadsheet.py
> +def allow_user_to_authenticate_google_account():
I DMed Victoria and Naveen the SERVICE_ACCOUNT_CREDENTIALS are created the service account for GradeSync on GCP

2024-11-09 01:51 UTC, closed without merging